import { MockAthlete } from '../types';

export const MOCK_ATHLETES: MockAthlete[] = [
  {
    id: 'athlete-001',
    name: 'Jordan Lee',
    sport: 'Basketball',
    recoveryScore: 82,
    sorenessScore: 3,
    streakDay: 9,
    sevenDaySoreness: [4, 6, 5, 3, 7, 4, 3],
  },
  {
    id: 'athlete-002',
    name: 'Maya Chen',
    sport: 'Swimming',
    recoveryScore: 71,
    sorenessScore: 5,
    streakDay: 5,
    sevenDaySoreness: [3, 4, 6, 7, 5, 6, 5],
  },
  {
    id: 'athlete-003',
    name: 'Tyler Brooks',
    sport: 'Track',
    recoveryScore: 58,
    sorenessScore: 7,
    streakDay: 2,
    sevenDaySoreness: [5, 6, 8, 7, 6, 8, 7],
  },
  {
    id: 'athlete-004',
    name: 'Aisha Patel',
    sport: 'Volleyball',
    recoveryScore: 91,
    sorenessScore: 2,
    streakDay: 14,
    sevenDaySoreness: [3, 2, 3, 4, 2, 3, 2],
  },
  {
    id: 'athlete-005',
    name: 'Marcus Ortega',
    sport: 'Soccer',
    recoveryScore: 44,
    sorenessScore: 8,
    streakDay: 1,
    sevenDaySoreness: [4, 5, 6, 8, 7, 9, 8],
  },
  {
    id: 'athlete-006',
    name: 'Riley Kim',
    sport: 'Gymnastics',
    recoveryScore: 67,
    sorenessScore: 6,
    streakDay: 6,
    sevenDaySoreness: [5, 7, 6, 5, 7, 6, 6],
  },
  {
    id: 'athlete-007',
    name: 'Devon Walsh',
    sport: 'Football',
    recoveryScore: 76,
    sorenessScore: 4,
    streakDay: 8,
    sevenDaySoreness: [6, 5, 4, 5, 3, 4, 4],
  },
  {
    id: 'athlete-008',
    name: 'Sofia Martinez',
    sport: 'Tennis',
    recoveryScore: 85,
    sorenessScore: 3,
    streakDay: 11,
    sevenDaySoreness: [3, 4, 3, 2, 4, 3, 3],
  },
];
